name: push_app
description: "Project to test push notifications with Firebase."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  equatable: ^2.0.5
  firebase_core: ^3.1.0
  firebase_messaging: ^15.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  go_router: ^14.1.4

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
